---
title: Configure OEM Information
description: Configures OEM information to contain the Atlas version and the Atlas Discord server
option: 'config-wOS'
actions:
  - !registryValue:
    path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\OEMInformation'
    value: 'Manufacturer'
    data: 'wave'
    type: REG_SZ
  - !registryValue:
    path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\OEMInformation'
    value: 'Model'
    data: 'waveOS v0.4.0'
    type: REG_SZ
  - !registryValue:
    path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\OEMInformation'
    value: 'SupportURL'
    data: 'https://gitlab.com/13waves/waveOS'
    type: REG_SZ
  - !registryValue:
    path: 'HKLM\SOFTWARE\Atlas'
    value: 'WinreFallbackFixed'
    data: '1'
    type: REG_SZ
